apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kmg-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kmg-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: kmg-root-ca
  secretName: kmg-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: kmg-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kmg-ca-issuer
spec:
  ca:
    secretName: kmg-ca-secret
